export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
		    enrollNo: "johndoe",
			profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
			fullName: "John Doe",
		},
		applications: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
		    enrollNo: "johndoe",
			profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
			fullName: "John Doe",
		},
		applications: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
		    enrollNo: "johndoe",
			profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
			fullName: "John Doe",
		},
		applications: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
		    enrollNo: "johndoe",
			profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
			fullName: "John Doe",
		},
		applications: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "John Doe",
	    enrollNo: "johndoe",
		profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
	},
	{
		_id: "2",
		fullName: "Jane Doe",
	    enrollNo: "janedoe",
		profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.pngg",
	},
	{
		_id: "3",
		fullName: "Bob Doe",
	    enrollNo: "bobdoe",
		profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.png",
	},
	{
		_id: "4",
		fullName: "Daisy Doe",
	    enrollNo: "daisydoe",
		profileImg: "https://cdn-icons-png.flaticon.com/512/6522/6522516.pngg",
	},
];